# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: Test-Free

on: workflow_dispatch

permissions:
  contents: read

jobs:

  clean-free:

    name: Space cleanup

    runs-on: ubuntu-latest

    steps:
      #- name: Space cleanup and Initialization environment
      #  env:
      #    DEBIAN_FRONTEND: noninteractive
      #  run: |
      #    docker rmi `docker images -q`
      #    sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
      #    sudo -E apt-mark hold grub-efi-amd64-signed
      #    sudo -E apt update
      #    sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
      #    sudo -E apt -y full-upgrade
      #    sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
      #    sudo -E systemctl daemon-reload
      #    sudo -E apt -y autoremove --purge
      #    sudo -E apt clean
      #    sudo -E timedatectl set-timezone "Asia/Shanghai"
      
      
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Install necessary app
        run: |
          echo 'Before 剩余空间：'
          df -h /
          sudo -E timedatectl set-timezone "Asia/Shanghai
          sudo -E systemctl daemon-reload
          sudo -E apt update
          sudo -E apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils python3-setuptools rsync swig unzip zlib1g-dev file wget
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          echo 'After 剩余空间：'
          df -h /