# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: Test-CI

on: workflow_dispatch

permissions:
  contents: read


jobs:

  build_mwrt:

    name: Build MWRT Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Checkout MWRT
        uses: actions/checkout@v4
        with: 
          ref: main
          path: 'mwrt'
      
      - name: Checkout immortalwrt
        uses: actions/checkout@v4
        with: 
          repository: immortalwrt/immortalwrt
          ref: ${{ vars.IMM_TAG }}
          path: 'imm'
      
      # 改预设文件内容，为其添加默认的密码LOGIN_PASSWD
      - name: add defaults uci-configs
        env:
          LOGIN_PASSWD: ${{ secrets.LOGIN_PASSWD }}
        run: |
          echo '改预设文件内容，为其添加默认的密码LOGIN_PASSWD'
          cd mwrt
          ls -al
          sed -i "1a LOGIN_PASSWD=$LOGIN_PASSWD" 99-custom
          echo '展示uci预设文件内容'
          cat 99-custom
          mkdir -p ../imm/files/etc/uci-defaults
          cp 99-custom ../imm/files/etc/uci-defaults/
      
      # 改feeds文件
      # 拉不在feeds中的文件
      # 把文件都放到对应目录中    
      - name: update imm
        run: |
          echo '改feeds文件，把它移到package'
          cd imm
          ls -al
          sed -i "1a src-git openclash https://github.com/vernesong/OpenClash.git" feeds.conf.default
          sed -i "1a src-git wrtbwmon https://github.com/brvphoenix/luci-app-wrtbwmon" feeds.conf.default
          sed -i "1a src-git wrtbwmon2 https://github.com/brvphoenix/wrtbwmon" feeds.conf.default
          echo '展示feeds配置文件内容：'
          cat feeds.conf.default
          cd ..
          git clone --depth=1 https://github.com/sirpdboy/luci-app-advanced.git
          mkdir -p imm/package/meta/
          cp -r luci-app-advanced imm/package/meta/
          echo '展示package'
          ls -aR imm/package
      
      
      - name: wor dir
        run: |
          echo '展示工作目录\n'
          pwd
          ls -al