# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: Test-CI

on: workflow_dispatch

permissions:
  contents: read

jobs:

  build_mwrt:

    name: Build MWRT Firmware

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout MWRT
        uses: actions/checkout@v4
        with: 
          ref: v23.05.5
        run: |
          pwd

      - name: work dir
        run: |
          echo '展示工作目录\n'
          pwd