# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: Test-CI

on: workflow_dispatch

permissions:
  contents: read

jobs:

  build_mwrt:

    name: Build MWRT Firmware

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout MWRT
        uses: actions/checkout@v4
        with: 
          ref: main

      - name: work dir 1
        run: |
          echo '展示工作目录\n'
          pwd
          ls -aRl
          cd /
          
      - name: work dir 1
        run: |
          echo '展示工作目录\n'
          pwd
          ls -aRl
          cd ../
      
      - name: Checkout MWRT
        uses: actions/checkout@v4
        with: 
          repository: immortalwrt/immortalwrt
          ref: v24.10.1 
          fetch-depth: '1'
      
      - name: wor dir 3
        run: |
          cd ../
          echo '展示工作目录\n'
          pwd
          ls -Rl